ALTER TABLE DM_PHUONG_XA ADD TOA_DO_BIEN_GIOI CLOB;
ALTER TABLE DM_PHUONG_XA ADD LON_CENTER NUMBER(10, 6);
ALTER TABLE DM_PHUONG_XA ADD LAT_CENTER NUMBER(10, 6);
ALTER TABLE DM_PHUONG_XA ADD MAX_LAT NUMBER(10, 6);
ALTER TABLE DM_PHUONG_XA ADD MIN_LAT NUMBER(10, 6);
ALTER TABLE DM_PHUONG_XA ADD MAX_LON NUMBER(10, 6);
ALTER TABLE DM_PHUONG_XA ADD MIN_LON NUMBER(10, 6);

ALTER TABLE DM_PHUONG_XA DROP COLUMN TOA_DO_BIEN_GIOI;
ALTER TABLE DM_PHUONG_XA DROP COLUMN WAY_ADDRESS;
ALTER TABLE DM_PHUONG_XA ADD POLYGON_DATA CLOB;


ALTER TABLE DMTT ADD TOA_DO_BIEN_GIOI CLOB;
ALTER TABLE DMTT ADD LON_CENTER NUMBER(10, 6);
ALTER TABLE DMTT ADD LAT_CENTER NUMBER(10, 6);
ALTER TABLE DMTT ADD MAX_LAT NUMBER(10, 6);
ALTER TABLE DMTT ADD MIN_LAT NUMBER(10, 6);
ALTER TABLE DMTT ADD MAX_LON NUMBER(10, 6);
ALTER TABLE DMTT ADD MIN_LON NUMBER(10, 6);

ALTER TABLE DMTT DROP COLUMN TOA_DO_BIEN_GIOI;
ALTER TABLE DMTT DROP COLUMN WAY_ADDRESS;
ALTER TABLE DMTT ADD POLYGON_DATA CLOB;


