ALTER TABLE DM_PHUONG_XA ADD TOA_DO_BIEN_GIOI CLOB;
ALTER TABLE DM_PHUONG_XA ADD LON_CENTER NUMBER(10, 6);
ALTER TABLE DM_PHUONG_XA ADD LAT_CENTER NUMBER(10, 6);
ALTER TABLE DM_PHUONG_XA ADD WAY_ADDRESS CLOB;


ALTER TABLE DMTT ADD TOA_DO_BIEN_GIOI CLOB;
ALTER TABLE DMTT ADD LON_CENTER NUMBER(10, 6);
ALTER TABLE DMTT ADD LAT_CENTER NUMBER(10, 6);
ALTER TABLE DMTT ADD WAY_ADDRESS CLOB;
