ALTER TABLE DM_PHUONG_XA ADD TOA_DO_BIEN_GIOI CLOB;
ALTER TABLE DM_PHUONG_XA ADD LON_CENTER NUMBER(10, 6);
ALTER TABLE DM_PHUONG_XA ADD LAT_CENTER NUMBER(10, 6);


ALTER TABLE DM_TT ADD TOA_DO_BIEN_GIOI CLOB;
ALTER TABLE DM_TT ADD LON_CENTER NUMBER(10, 6);
ALTER TABLE DM_TT ADD LAT_CENTER NUMBER(10, 6);
